name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          only-new-issues: false
          args: --timeout 5m --config .rules/.golangci.yml
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.15
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Tools
        run: make tools-go
      - name: Test
        run: make test-all